esphome:
  name: smart-door
  on_boot:
    - priority: 600
      then: # Power connected = closed, lock after delay
        - delay: 3s
        - number.set:
            id: servo_number
            value: 100
        - delay: 3s
        - number.set:
            id: servo_number
            value: 0

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Ab-Apart"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Door Fallback Hotspot"
    password: !secret ap_password

captive_portal:
    
# UI Controls
number:
  - platform: template
    id: servo_number
    name: Servo Control
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: servo_hw
            level: !lambda 'return x / 100.0;'

button:
  # Most components have REST API, read more: https://esphome.io/web-api/#api-rest
  - platform: template
    name: Servo Open
    id: servo_open
    # Equivalent: http://smart-door.local/button/servo_open/press
    on_press:
      then:
        - number.set:
            id: servo_number
            value: -100
        - delay: 3s
        - number.set:
            id: servo_number
            value: 0
  - platform: template
    name: Servo Close
    id: servo_close
    on_press:
      then:
        - number.set:
            id: servo_number
            value: 100
        - delay: 3s
        - number.set:
            id: servo_number
            value: 0
  - platform: template
    name: Servo Zero
    id: servo_zero
    on_press:
      then:
        - number.set:
            id: servo_number
            value: 0

# Hardwares
binary_sensor:
  # Optional, only when using a battery (always on)
  - platform: gpio
    id: door_sensor
    name: Door Sensor
    device_class: door
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
        # Means door is closed on release
    filters:
      - delayed_on_off: 1s
    on_release:
      then: # Auto-lock when door is closed
        - number.set:
            id: servo_number
            value: 100
        - delay: 3s
        - number.set:
            id: servo_number
            value: 0

servo:
  - id: servo_hw
    output: servo_pwm_output

output:
  - platform: ledc
    id: servo_pwm_output
    pin: GPIO13
    frequency: 50Hz

web_server:
  version: 3
  port: 80