esphome:
  name: smart-door

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Ab-Apart"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Door Fallback Hotspot"
    password: !secret ap_password

captive_portal:
    
number:
  - platform: template
    id: servo_number
    name: Servo Control
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: servo_hw
            level: !lambda 'return x / 100.0;'

button:
  - platform: template
    name: Servo Zero
    on_press:
      then:
        - number.set:
            id: servo_number
            value: 0

servo:
  - id: servo_hw
    output: servo_pwm_output

output:
  - platform: ledc
    id: servo_pwm_output
    pin: GPIO13
    frequency: 50Hz

web_server:
  port: 80